Repository uniworld-io/unichain-core, pull requests merged in 2021-12, with the labels that each got.

#15 - add License, security, contribute, release guide
  CONTRIBUTING.md
  LICENSE
  RELEASE.md
  SECURITY.md
Labels: documentation

#16 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#21 - force check token's critical update when transfer/exchange token
  src/main/java/org/unichain/core/actuator/TokenBurnActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenCreateActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenExchangeActuator.java
  src/main/java/org/unichain/core/actuator/TokenMineActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenTransferActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenTransferOwnerActuator.java
  src/main/java/org/unichain/core/actuator/TokenUpdateParamsActuatorV3.java
  src/main/java/org/unichain/core/capsule/TokenPoolCapsule.java
  src/main/java/org/unichain/core/config/Parameter.java
  src/main/java/org/unichain/core/services/http/utils/Util.java
  src/main/protos/core/Contract.proto
Labels: enhancement

#23 - fix: set latest token operation time
  src/main/java/org/unichain/core/actuator/TokenBurnActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenContributePoolFeeActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenExchangeActuator.java
  src/main/java/org/unichain/core/actuator/TokenMineActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenTransferOwnerActuator.java
  src/main/java/org/unichain/core/actuator/TokenUpdateParamsActuatorV3.java
Labels: bug, enhancement

#30 - Exchange urc30: update expire time limit
  src/main/java/org/unichain/common/runtime/RuntimeImpl.java
  src/main/java/org/unichain/core/actuator/AssetIssueActuator.java
  src/main/java/org/unichain/core/actuator/BuyStorageActuator.java
  src/main/java/org/unichain/core/actuator/BuyStorageBytesActuator.java
  src/main/java/org/unichain/core/actuator/ExchangeCreateActuator.java
  src/main/java/org/unichain/core/actuator/ExchangeInjectActuator.java
  src/main/java/org/unichain/core/actuator/ParticipateAssetIssueActuator.java
  src/main/java/org/unichain/core/actuator/ProposalApproveActuator.java
  src/main/java/org/unichain/core/actuator/ProposalDeleteActuator.java
  src/main/java/org/unichain/core/actuator/SellStorageActuator.java
  src/main/java/org/unichain/core/actuator/SetAccountIdActuator.java
  src/main/java/org/unichain/core/actuator/TokenBurnActuator.java
  src/main/java/org/unichain/core/actuator/TokenContributePoolFeeActuator.java
  src/main/java/org/unichain/core/actuator/TokenContributePoolFeeActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenCreateActuator.java
  src/main/java/org/unichain/core/actuator/TokenCreateActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenExchangeActuator.java
  src/main/java/org/unichain/core/actuator/TokenTransferActuator.java
  src/main/java/org/unichain/core/actuator/TokenTransferActuatorV3.java
  src/main/java/org/unichain/core/actuator/TokenTransferOwnerActuator.java
  src/main/java/org/unichain/core/actuator/TransferAssetActuator.java
  src/main/java/org/unichain/core/actuator/TransferFutureActuatorV3.java
  src/main/java/org/unichain/core/actuator/UnfreezeAssetActuator.java
  src/main/java/org/unichain/core/actuator/UnfreezeBalanceActuator.java
  src/main/java/org/unichain/core/actuator/UpdateAssetActuator.java
  src/main/java/org/unichain/core/actuator/UpdateBrokerageActuator.java
  src/main/java/org/unichain/core/actuator/VoteWitnessActuator.java
  src/main/java/org/unichain/core/actuator/WithdrawBalanceActuator.java
  src/main/java/org/unichain/core/config/Parameter.java
  src/main/java/org/unichain/core/db/DynamicPropertiesStore.java
  src/main/java/org/unichain/core/db/Manager.java
  src/main/java/org/unichain/core/db/TransactionTrace.java
  src/main/java/org/unichain/core/net/UnichainNetDelegate.java
  src/main/java/org/unichain/core/services/ProposalService.java
  src/main/java/org/unichain/program/FullNode.java
Labels: enhancement

#31 - force checking token exchange factors
  src/main/java/org/unichain/core/actuator/TokenExchangeActuator.java
Labels: enhancement

#32 - preset exchange factors to zero with block ver <= 2
  src/main/java/org/unichain/core/actuator/TokenCreateActuator.java
Labels: enhancement

#34 Fix token fee on non exist account
  src/main/java/org/unichain/core/actuator/TokenTransferActuatorV3.java
  src/main/java/org/unichain/core/config/Parameter.java
  src/main/java/org/unichain/core/db/BandwidthProcessorV2.java
  src/main/java/org/unichain/core/db/BandwidthProcessorV3.java
  src/main/java/org/unichain/core/db/Manager.java
Labels: enhancement

#36 - fix validation of token transfer fee
  src/main/java/org/unichain/core/actuator/TokenTransferActuatorV3.java
Labels: bug
